name: tfm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=17
  - pyspark
  - pyarrow
  - pandas
  - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - streamlit

